### ISSUE TITLE
playtest result / plan

### ISSUE THREAD

**Issue by thomamason** [thomamason/text-adventure-game#1]
## cass playtest 

- [ ] 'old guys at the back' encounter is broken
- [ ] change command class to only read enter key
    - buffer to read key?
-  figure out how to reject key entry registering on screen unless needed

##### to-do
- [ ] add rudimentary hud
- - time of day
      - visual style (MM:HH AM/PM)
      - each encounter adds X minutes to time
 - - hp
 - - mp
 - - points
